/**
 * Copyright (c) Microsoft. All rights reserved.
 * This code is licensed under the MIT License (MIT).
 * THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
 * ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
 * IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
 *
 * Advanced Technology Group (ATG)
 *
 * AUTO-GENERATED by zstdgpu_srt_tool.exe. DO NOT EDIT.
 * Source of truth: zstdgpu_srt_decl.h
 */

#ifndef ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_PlainDispatchIndirect_H
#define ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_PlainDispatchIndirect_H

#ifdef __hlsl_dx_compiler

#define ZSTDGPU_SRT_RS_BIND_GROUP_PlainDispatchIndirect "DescriptorTable(SRV(t0, space=1, numDescriptors=1))"

ZSTDGPU_RO_BUFFER(uint32_t) ZstdInDispatchArgs  : register(t0, space1);

template<typename T>
static void zstdgpu_Srt_FillBindGroup_PlainDispatchIndirect(ZSTDGPU_PARAM_INOUT(T) srt)
{
    srt.inDispatchArgs  = ZstdInDispatchArgs;
}

#else

template<typename T>
static void zstdgpu_Srt_FillBindGroup_PlainDispatchIndirect(T &srt, const zstdgpu_ResourceDataCpu &cpuRes)
{
    srt.inDispatchArgs  = cpuRes.DispatchArgs;
}

#endif /* #ifdef __hlsl_dx_compiler */
#endif /* ZSTDGPU_SRT_GENERATED_RS_BIND_GROUP_PlainDispatchIndirect_H */
